### ISSUE TITLE
Info for users running MSYS2/Git for Windows shells

### ISSUE THREAD

**Issue by tkf144** [rnowley/csharp-ncurses#1]
Hi Raymond,

Thanks for providing this library. I'm beginning to dabble in an ncurses project and it should prove helpful.

I had some small issues getting the Hello World sample running on Windows 10 using Git Bash inside ConEmu, and thought it may benefit someone else if it were documented. I'm not sure if this is assumed knowledge for the target audience of your library (or even a legitimate issue), so I have not submitted a PR to amend `README.md`, nor created a Wiki page.

Learnings:
* Get `libncursesw6.dll`. Version 6.1 available [here]( https://invisible-island.net/ncurses/#download_mingw-h3) as of 04-2018.
    * Place it somewhere that features in `%PATH%`.
    * Reference it in `..\csharp-ncurses\csharp-ncurses\NativeMethods.cs`
* Start a Bash shell. I use ConEmu, via a task which runs the following: `"C:\Program Files\Git\git-cmd.exe" --no-cd --command=usr/bin/bash.exe -l -i`:
    * `pwd` -> `[..]/sample/helloWorld`
    * `echo $TERM` -> `cygwin`
    * `dotnet build`
    * `dotnet run` -> `Error opening terminal: cygwin.`
    * `export TERMINFO="C:\Program Files\Git\usr\lib\terminfo"`
    * `dotnet run` -> `Goodbye cruel #C programming` as expected

Pointing ncurses to the Cygwin terminfo file (`"C:\Program Files\Git\usr\lib\terminfo\63\cygwin"`) via `$TERMINFO` seems to be the key. Mintty (what `git-bash.exe` wraps) launches Bash with `$TERM=xterm, $TERMINFO=`, and can run the Hello World sample OK, but it seems `git-cmd.exe`, running Bash, requires setting `$TERMINFO`.

Hope that helps someone.

Cheers,
Tom

**Comment by rnowley** [comment]
Hello Tom,
I'm glad that you have found this library useful. I have only just started working on this library again and I will look to add some documentation around it's use. Feel free to submit a pull request with instructions of how to get it to run on Windows 10 using Git Bash inside ConEmu.

Regards,
Raymond

**Comment by tkf144** [comment]
Cheers Raymond,

Have put the gist of this issue on the Wiki and submitted a PR to stick a link to the wiki in the `README.md`.

Thanks again.
Tom
